=== AlikZan/KOIB/Croc.Bpc/Printing/Data/Schemas/ReportTemplate.xsd
<?xml version="1.0" encoding="windows-1251"?> 

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://localhost/Schemas/SIB2003/ReportTemplate"

targetNamespace="http://localhost/Schemas/SIB2003/ReportTemplate" elementFormDefault="qualified"> 

	<xs:element name="ReportTemplate"> 

		<xs:annotation> 

			<xs:documentation>???????? ??????? ??????</xs:documentation> 

		</xs:annotation> 

		<xs:complexType> 

			<xs:sequence> 

				<xs:element name="Parameters" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>????????? ??????</xs:documentation> 

					</xs:annotation> 

					<xs:complexType> 

						<xs:sequence> 

							<xs:element name="Parameter" type="xs:string" maxOccurs="unbounded"> 

								<xs:annotation> 

									<xs:documentation>???????? ?????????</xs:documentation> 

								</xs:annotation> 

							</xs:element> 

						</xs:sequence> 

					</xs:complexType> 

				</xs:element> 

				<xs:element name="Header" type="PlainContent" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>????????? ??????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="PageHeader" type="PlainContent" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>???????????? ?????????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="Table" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>???? ??????</xs:documentation> 

					</xs:annotation> 

					<xs:complexType> 

						<xs:complexContent> 

							<xs:extension base="TableContent"> 

								<xs:attribute name="dotted" type="xs:boolean"> 

									<xs:annotation> 

										<xs:documentation>??????? ?????????? ?????? ???? ? ??????? ???????</xs:documentation> 

									</xs:annotation> 

								</xs:attribute> 

							</xs:extension> 

						</xs:complexContent> 

					</xs:complexType> 

				</xs:element> 

				<xs:element name="PageFooter" type="PlainContent" minOccurs="0"> 


					<xs:annotation> 

						<xs:documentation>???????????? ??????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="Footer" type="PlainContent" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>?????? ??????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

			</xs:sequence> 

			<xs:attribute name="name" type="xs:string" use="required"> 

				<xs:annotation> 

					<xs:documentation>??? ??????</xs:documentation> 

				</xs:annotation> 

			</xs:attribute> 

			<xs:attribute name="restriction" type="xs:string"> 

				<xs:annotation> 

					<xs:documentation>??????????? ?? ?????????? ??????</xs:documentation> 

				</xs:annotation> 

			</xs:attribute> 

			<xs:attribute name="claspFooter" type="xs:boolean" default="true"> 

				<xs:annotation> 

					<xs:documentation>??????? ???????? ??????? ? ??????</xs:documentation> 

				</xs:annotation> 

			</xs:attribute> 

			<xs:attribute name="pageNumbered" type="xs:boolean" default="true"> 

				<xs:annotation> 

					<xs:documentation>??????? ????????????? ?????? ??????? ???????</xs:documentation> 

				</xs:annotation> 

			</xs:attribute> 

		</xs:complexType> 

	</xs:element> 

	<xs:complexType name="IfClause"> 

		<xs:attribute name="condition" type="xs:string" use="required"> 

			<xs:annotation> 

				<xs:documentation>???????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

		<xs:attribute name="not" type="xs:boolean"> 

			<xs:annotation> 

				<xs:documentation>???????? ???????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

	</xs:complexType> 

	<xs:complexType name="PlainIfClause"> 

		<xs:complexContent> 

			<xs:extension base="IfClause"> 

				<xs:sequence> 

					<xs:element name="Then" type="PlainContent" minOccurs="0"> 

						<xs:annotation> 


							<xs:documentation>??????????? ??? ?????????? ???????</xs:documentation> 

						</xs:annotation> 

					</xs:element> 

					<xs:element name="Else" type="PlainContent" minOccurs="0"> 

						<xs:annotation> 

							<xs:documentation>??????????? ??? ???????? ???????</xs:documentation> 

						</xs:annotation> 

					</xs:element> 

				</xs:sequence> 

			</xs:extension> 

		</xs:complexContent> 

	</xs:complexType> 

	<xs:complexType name="TableIfClause"> 

		<xs:complexContent> 

			<xs:extension base="IfClause"> 

				<xs:sequence> 

					<xs:element name="Then" type="TableBody" minOccurs="0"> 

						<xs:annotation> 

							<xs:documentation>??????????? ? ?????? ?????????? ???????</xs:documentation> 

						</xs:annotation> 

					</xs:element> 

					<xs:element name="Else" type="TableBody" minOccurs="0"> 

						<xs:annotation> 

							<xs:documentation>??????????? ? ?????? ???????? ???????</xs:documentation> 

						</xs:annotation> 

					</xs:element> 

				</xs:sequence> 

			</xs:extension> 

		</xs:complexContent> 

	</xs:complexType> 

	<xs:complexType name="PlainContent"> 

		<xs:sequence minOccurs="0" maxOccurs="unbounded"> 

			<xs:choice> 

				<xs:element name="Line" minOccurs="0" maxOccurs="unbounded"> 

					<xs:annotation> 

						<xs:documentation>?????? ??????</xs:documentation> 

					</xs:annotation> 

					<xs:complexType mixed="true"> 

						<xs:complexContent mixed="true"> 

							<xs:extension base="PlainLine"/> 

						</xs:complexContent> 

					</xs:complexType> 

				</xs:element> 

				<xs:element name="If" type="PlainIfClause" minOccurs="0" maxOccurs="unbounded"> 

					<xs:annotation> 

						<xs:documentation>???????? ????????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="For" type="PlainForClause" minOccurs="0" maxOccurs="unbounded"> 

					<xs:annotation> 


						<xs:documentation>????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="SetCurrentRow" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>????????? ?????? ??????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

			</xs:choice> 

		</xs:sequence> 

	</xs:complexType> 

	<xs:complexType name="TableBody"> 

		<xs:sequence minOccurs="0" maxOccurs="unbounded"> 

			<xs:choice> 

				<xs:element name="Line" minOccurs="0" maxOccurs="unbounded"> 

					<xs:annotation> 

						<xs:documentation>?????? ???????</xs:documentation> 

					</xs:annotation> 

					<xs:complexType> 

						<xs:complexContent> 

							<xs:extension base="TableLine"> 

								<xs:attributeGroup ref="IfCondition"/> 

							</xs:extension> 

						</xs:complexContent> 

					</xs:complexType> 

				</xs:element> 

				<xs:element name="If" type="TableIfClause" minOccurs="0" maxOccurs="unbounded"> 

					<xs:annotation> 

						<xs:documentation>???????? ????????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="For" type="TableForClause" minOccurs="0" maxOccurs="unbounded"> 

					<xs:annotation> 

						<xs:documentation>????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="SetCurrentRow" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>????????? ?????? ??????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

			</xs:choice> 

		</xs:sequence> 

	</xs:complexType> 

	<xs:complexType name="PlainForClause"> 

		<xs:sequence> 

			<xs:element name="Body" type="PlainContent"> 

				<xs:annotation> 

					<xs:documentation>???? ?????</xs:documentation> 

				</xs:annotation> 


			</xs:element> 

		</xs:sequence> 

		<xs:attributeGroup ref="ForCondition"/> 

	</xs:complexType> 

	<xs:complexType name="LinePart" mixed="true"> 

		<xs:sequence> 

			<xs:element name="Parts" minOccurs="0"> 

				<xs:annotation> 

					<xs:documentation>?????????</xs:documentation> 

				</xs:annotation> 

				<xs:complexType> 

					<xs:sequence> 

						<xs:element name="Part" type="LinePart" minOccurs="0" maxOccurs="unbounded"> 

							<xs:annotation> 

								<xs:documentation>???????? ?????????</xs:documentation> 

							</xs:annotation> 

						</xs:element> 

					</xs:sequence> 

				</xs:complexType> 

			</xs:element> 

		</xs:sequence> 

		<xs:attributeGroup ref="IfCondition"/> 

	</xs:complexType> 

	<xs:complexType name="TableForClause"> 

		<xs:sequence> 

			<xs:element name="Body" type="TableBody"> 

				<xs:annotation> 

					<xs:documentation>???? ?????</xs:documentation> 

				</xs:annotation> 

			</xs:element> 

		</xs:sequence> 

		<xs:attributeGroup ref="ForCondition"/> 

	</xs:complexType> 

	<xs:attributeGroup name="ForCondition"> 

		<xs:attribute name="each" type="xs:string" use="required"> 

			<xs:annotation> 

				<xs:documentation>?????????? ?????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

		<xs:attribute name="in" type="xs:string" use="required"> 

			<xs:annotation> 

				<xs:documentation>?????????, ?? ??????? ??????????? ????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

	</xs:attributeGroup> 

	<xs:attributeGroup name="IfCondition"> 

		<xs:attribute name="condition" type="xs:string"> 

			<xs:annotation> 

				<xs:documentation>???????</xs:documentation> 

			</xs:annotation> 


		</xs:attribute> 

		<xs:attribute name="not" type="xs:boolean"> 

			<xs:annotation> 

				<xs:documentation>???????? ????????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

	</xs:attributeGroup> 

	<xs:complexType name="TableContent"> 

		<xs:sequence> 

			<xs:element name="Header"> 

				<xs:annotation> 

					<xs:documentation>???????? ???????? ???????</xs:documentation> 

				</xs:annotation> 

				<xs:complexType> 

					<xs:sequence> 

						<xs:element name="Col" maxOccurs="unbounded"> 

							<xs:annotation> 

								<xs:documentation>???????? ???????</xs:documentation> 

							</xs:annotation> 

							<xs:complexType mixed="true"> 

								<xs:attributeGroup ref="FontDefinition"/> 

								<xs:attribute name="width" type="xs:int"> 

									<xs:annotation> 

										<xs:documentation>?????? ??????? ? %</xs:documentation> 

									</xs:annotation> 

								</xs:attribute> 

								<xs:attribute name="count" type="xs:string"> 

									<xs:annotation> 

										<xs:documentation>?????????, ?? ?????????? ????????? ??????? ????? ????????? ???????</xs:documentation> 

									</xs:annotation> 

								</xs:attribute> 

							</xs:complexType> 

						</xs:element> 

					</xs:sequence> 

				</xs:complexType> 

			</xs:element> 

			<xs:element name="Body" type="TableBody"> 

				<xs:annotation> 

					<xs:documentation>???? ???????</xs:documentation> 

				</xs:annotation> 

			</xs:element> 

		</xs:sequence> 

	</xs:complexType> 

	<xs:attributeGroup name="FontDefinition"> 

		<xs:attribute name="fontSize" type="xs:string"> 

			<xs:annotation> 

				<xs:documentation>?????? ??????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

		<xs:attribute name="bold" type="xs:boolean"> 


			<xs:annotation> 

				<xs:documentation>??????? ??????? ??????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

		<xs:attribute name="italic" type="xs:boolean"> 

			<xs:annotation> 

				<xs:documentation>??????? ?????????? ??????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

		<xs:attribute name="align" type="Croc.SibApp.Printing.LineAlign"> 

			<xs:annotation> 

				<xs:documentation>????????????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

	</xs:attributeGroup> 

	<xs:complexType name="PlainLine" mixed="true"> 

		<xs:complexContent mixed="true"> 

			<xs:extension base="LinePart"> 

				<xs:attributeGroup ref="FontDefinition"/> 

				<xs:attribute name="split" type="xs:string"> 

					<xs:annotation> 

						<xs:documentation>??????(?) ?? ??????? ?????? ??????????? ?? ?????????</xs:documentation> 

					</xs:annotation> 

				</xs:attribute> 

				<xs:attribute name="trim" type="xs:boolean"> 

					<xs:annotation> 

						<xs:documentation>??????? ???????? ???????? ? ????? ?????? ??????</xs:documentation> 

					</xs:annotation> 

				</xs:attribute> 

			</xs:extension> 

		</xs:complexContent> 

	</xs:complexType> 

	<xs:complexType name="TableLine"> 

		<xs:sequence> 

			<xs:element name="Cols"> 

				<xs:annotation> 

					<xs:documentation>??????? ??????</xs:documentation> 

				</xs:annotation> 

				<xs:complexType> 

					<xs:sequence> 

						<xs:element name="Col" maxOccurs="unbounded"> 

							<xs:annotation> 

								<xs:documentation>???????</xs:documentation> 

							</xs:annotation> 

							<xs:complexType mixed="true"> 

								<xs:complexContent mixed="true"> 

									<xs:extension base="LinePart"> 

										<xs:attribute name="each" type="xs:string"> 

											<xs:annotation> 

												<xs:documentation>?????????? ?????</xs:documentation> 


											</xs:annotation> 

										</xs:attribute> 

										<xs:attribute name="in" type="xs:string"> 

											<xs:annotation> 

												<xs:documentation>?????????, ?? ??????? ???????? ???????</xs:documentation> 

											</xs:annotation> 

										</xs:attribute> 

									</xs:extension> 

								</xs:complexContent> 

							</xs:complexType> 

						</xs:element> 

					</xs:sequence> 

				</xs:complexType> 

			</xs:element> 

		</xs:sequence> 

		<xs:attributeGroup ref="ColDefinition"/> 

		<xs:attribute name="newPage" type="xs:boolean" default="false"> 

			<xs:annotation> 

				<xs:documentation>??????? ???????? ?? ????????? ????????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

	</xs:complexType> 

	<xs:attributeGroup name="ColDefinition"> 

		<xs:attributeGroup ref="FontDefinition"/> 

		<xs:attribute name="dotted" type="xs:boolean"> 

			<xs:annotation> 

				<xs:documentation>??????? ?????????? ?????? ???????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

	</xs:attributeGroup> 

	<xs:simpleType name="Croc.SibApp.Printing.LineAlign"> 

		<xs:annotation> 

			<xs:documentation>Croc.SibApp.Printing.LineAlign</xs:documentation> 

		</xs:annotation> 

		<xs:restriction base="xs:string"> 

			<xs:enumeration value="Left"> 

				<xs:annotation> 

					<xs:documentation>???????????? ?? ?????? ????</xs:documentation> 

				</xs:annotation> 

			</xs:enumeration> 

			<xs:enumeration value="Right"> 

				<xs:annotation> 

					<xs:documentation>???????????? ?? ??????? ????</xs:documentation> 

				</xs:annotation> 

			</xs:enumeration> 

			<xs:enumeration value="Center"> 

				<xs:annotation> 

					<xs:documentation>???????????? ?? ??????</xs:documentation> 

				</xs:annotation> 

			</xs:enumeration> 


		</xs:restriction> 

	</xs:simpleType> 

</xs:schema>

=== AlikZan/KOIB/Croc.Bpc/Printing/Data/Templates/FailedControlRelations.xml
<?xml version="1.0" encoding="windows-1251"?> 

<!-- ?? ????????????? ??????????? ??????????? --> 

<ReportTemplate name="FailedControlRelations" pageNumbered="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

xmlns="http://localhost/Schemas/SIB2003/ReportTemplate" xsi:schemaLocation="http://localhost/Schemas/SIB2003/ReportTemplate ReportTemplate.xsd"> 

	<Parameters> 

		<!-- ??????, ?? ?????? ??????? ??????????? ????? --> 

		<Parameter>Election</Parameter> 

	</Parameters> 

	<Header> 

		<Line>?? ????????????? ??????????? ???????????</Line> 

		<Line>??????? ???? ? ?????: {$CurrentDateTime|dd.MM.yyyy HH:mm:ss}</Line> 

		<Line/> 

		<If condition="ElectionManager.HasSourceData"> 

			<Then> 

				<If condition="@Election.Protocol.Checks"> 

					<Then> 

						<If not="true" condition="@Election.KSTurnedOff"> 

							<Then> 

								<For each="Check" in="@Election.Protocol.Checks"> 

									<Body> 

										<!-- ???????? ??????? ?? --> 

										<If condition="@Check.Enabled"> 

											<Then> 

												<If condition="@Check.Failed"> 

													<Then> 

														<Line> 

															<Parts> 

																<Part>{$TAB}{$TAB}{$TAB}</Part> 

																<Part condition="@Check.Mild"> 

																	<Parts> 

																		<Part>[??????????] </Part> 

																	</Parts> 

																</Part> 

																<Part>{$@Check.GetFullExpression&lt;$@Election.Protocol;$ElectionManager.VotingResults&gt;}</Part> 

															</Parts> 

														</Line> 

														<!-- ? ?? ??????????? --> 

														<Line>{$TAB}{$TAB}{$TAB}{$@Check.GetExpansion&lt;$@Election.Protocol&gt;}</Line> 

														<Line>{$CRLF}</Line> 

													</Then> 

												</If> 

											</Then> 

										</If> 

									</Body> 

								</For> 

								<Line/> 

								<If condition="@Election.NoneAboveExists"> 

									<Then> 

										<Line>{$TAB}{$TAB}P =

{$ElectionManager.VotingResults.VotesCount&lt;$VoteKey.ctor&lt;;;;$@Election.NoneAboveCandidate.Id;$@Election.ElectionId;&gt;&gt;}</Line> 


									</Then> 

								</If> 

								<Line>{$TAB}{$TAB}M = {$@Election.MaxMarks}</Line> 

								<Line>{$TAB}{$TAB}S = {$ElectionManager.VotingResults.VotesCount&lt;$VoteKey.ctor&lt;;;;;$@Election.ElectionId;&gt;&gt;}</Line> 

								<For each="Line" in="@Election.Protocol.Lines"> 

									<Body> 

										<Line>{$TAB}{$TAB}{$@Line.@Current}. {$@Line.num}{$@Line.additionalNum} = {$@Line.Value}</Line> 

									</Body> 

								</For> 

							</Then> 

							<Else> 

								<Line>??????????? ??????????? ?????????</Line> 

							</Else> 

						</If> 

					</Then> 

					<Else> 

						<!-- ???? ?? ?????????? ?? ?????? ??... --> 

						<Line>{$TAB}{$TAB}??????????? ???????????: ???</Line> 

					</Else> 

				</If> 

			</Then> 

			<Else> 

				<Line>???????? ?????? ??? ?? ????????</Line> 

			</Else> 

		</If> 

	</Header> 

</ReportTemplate>

=== AlikZan/KOIB/Croc.Bpc/Printing/Data/Templates/ElectionProtocol_Narrow.xml
<?xml version="1.0" encoding="utf-8"?> 
<ReportTemplate claspFooter="true" name="ElectionProtocol" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://localhost/Schemas/SIB2003/ReportTemplate"
si:schemaLocation="http://localhost/Schemas/SIB2003/ReportTemplate ReportTemplate.xsd"> 
  <Parameters> 


    <Parameter>Election</Parameter> 


    <Parameter>withResults</Parameter> 
  </Parameters> 
  <Header> 
    <Line align="Left">–≠–∫–∑–µ–º–ø–ª—è—Ä ‚Ññ ___</Line> 
    <Line align="Center">{$@Election.Name}</Line> 
    <Line align="Center">{$ElectionManager.SourceData.ElectionDate|d MMMM yyyy –≥–æ–¥–∞}</Line> 
    <Line align="Center" bold="true">–ü–†–û–¢–û–ö–û–õ</Line> 
    <Line align="Center" split="\n" trim="true">{$@Election.Protocol.Name}</Line> 
    <Line align="Center">–ò–∑–±–∏—Ä–∞—Ç–µ–ª—å–Ω—ã–π —É—á–∞—Å—Ç–æ–∫ N{$ElectionManager.SourceData.Uik}</Line> 
  </Header> 
  <Body> 
    <Table> 
      <Header> 


        <Col width="3"/> 


        <Col width="65"/> 


        <Col width="4"/> 


        <Col width="28"/> 
      </Header> 
      <Body> 


        <For in="@Election.Protocol.Lines" each="Line"> 
          <Body> 
            <Line> 
              <Cols> 
                <Col>{$@Line.Num}{$@Line.AdditionalNum}</Col> 
                <Col>{$@Line.Name}</Col> 
                <Col> 
                  <Parts> 
                    <Part condition="@withResults">{$@Line.Value}</Part> 
                    <Part not="true" condition="@withResults">0</Part> 
                  </Parts> 
                </Col> 
                <Col> 
                  <Parts> 
                    <Part condition="@withResults">({$@Line.Value|#w})</Part> 
                    <Part not="true" condition="@withResults">(–Ω–æ–ª—å)</Part> 
                  </Parts> 
                </Col> 
              </Cols> 
            </Line> 
          </Body> 
        </For> 


        <SetCurrentRow>{$@Election.Protocol.LatestLineNumber}</SetCurrentRow> 


        <For in="@Election.Candidates" each="Candidate"> 
          <Body> 
            <If not="true" condition="@Candidate.Disabled"> 
              <Then> 


                <Line> 
                  <Cols> 
                    <Col>{$CurrentRow}</Col> 
                    <Col> 
                      <Parts> 
                        <Part condition="@Candidate.LastName">{$@Candidate.LastName|#u}</Part> 
                        <Part condition="@Candidate.FirstName"> {$@Candidate.FirstName}</Part> 
                        <Part condition="@Candidate.Patronymic"> {$@Candidate.Patronymic}</Part> 
                      </Parts> 
                    </Col> 
                    <Col> 
                      <Parts> 
                        <Part
ondition="@withResults">{$VotingResultManager.VotingResults.VotesCount&lt;$VoteKey.ctor&lt;;;;$@Candidate.Id;$@Election.ElectionId;&gt;&gt;}</Part> 
                        <Part not="true" condition="@withResults">0</Part> 
                      </Parts> 
                    </Col> 
                    <Col> 
                      <Parts> 
                        <Part
ondition="@withResults">({$VotingResultManager.VotingResults.VotesCount&lt;$VoteKey.ctor&lt;;;;$@Candidate.Id;$@Election.ElectionId;&gt;&gt;|#w})</Part> 
                        <Part not="true" condition="@withResults">(–Ω–æ–ª—å)</Part> 
                      </Parts> 
                    </Col> 
                  </Cols> 
                </Line> 
              </Then> 
              <Else> 


                <If condition="@Election.Protocol.DisabledString"> 
                  <Then> 


                    <Line> 
                      <Cols> 
                        <Col>{$CurrentRow}</Col> 
                        <Col> 
                          <Parts> 
                            <Part condition="@Candidate.LastName">{$@Candidate.LastName|#u}</Part> 
                            <Part condition="@Candidate.FirstName"> {$@Candidate.FirstName}</Part> 
                            <Part condition="@Candidate.Patronymic"> {$@Candidate.Patronymic}</Part> 
                          </Parts> 
                        </Col> 
                        <Col>{$@Election.Protocol.DisabledString}</Col> 
                        <Col/> 
                      </Cols> 
                    </Line> 
                  </Then> 
                </If> 
              </Else> 
            </If> 
          </Body> 
        </For> 
      </Body> 
    </Table> 
  </Body> 
  <PageFooter> 
            <Line align="Left"/> 
      <Line align="Left">–ü—Ä–µ–¥—Å–µ–¥–∞—Ç–µ–ª—å —É—á–∞—Å—Ç–∫–æ–≤–æ–π –∏–∑–±–∏—Ä–∞—Ç–µ–ª—å–Ω–æ–π –∫–æ–º–∏—Å—Å–∏–∏</Line> 
      <If not="true" condition="ElectionManager.SourceData.GetCommitteeMemberInitialByType&lt;Chairman&gt;"> 
        <Then> 
          <Line align="Right">______________________    _________________________________________</Line> 
        </Then> 
        <Else> 
          <Line align="Right">{$ElectionManager.SourceData.GetCommitteeMemberInitialByType&lt;Chairman&gt;}    _________________________________________</Line> 
        </Else> 
      </If> 
      <Line align="Right">(—Ñ–∞–º–∏–ª–∏—è, –∏–Ω–∏—Ü–∏–∞–ª—ã)                            (–ø–æ–¥–ø–∏—Å—å –ª–∏–±–æ –ø—Ä–∏—á–∏–Ω–∞ –æ—Ç—Å—É—Ç—Å—Ç–≤–∏—è,    </Line> 
      <Line align="Right">                                     –æ—Ç–º–µ—Ç–∫–∞ –æ–± –æ—Å–æ–±–æ–º –º–Ω–µ–Ω–∏–∏)         </Line> 
      <Line align="Left">–ó–∞–º–µ—Å—Ç–∏—Ç–µ–ª—å –ø—Ä–µ–¥—Å–µ–¥–∞—Ç–µ–ª—è –∫–æ–º–∏—Å—Å–∏–∏</Line> 
      <If not="true" condition="ElectionManager.SourceData.GetCommitteeMemberInitialByType&lt;ChairmanAssistant&gt;"> 
        <Then> 
          <Line align="Right">______________________    _________________________________________</Line> 
        </Then> 
        <Else> 
          <Line align="Right">{$ElectionManager.SourceData.GetCommitteeMemberInitialByType&lt;ChairmanAssistant&gt;}
________________________________________</Line> 
        </Else> 
      </If> 
      <Line align="Left">–°–µ–∫—Ä–µ—Ç–∞—Ä—å –∫–æ–º–∏—Å—Å–∏–∏</Line> 
      <If not="true" condition="ElectionManager.SourceData.GetCommitteeMemberInitialByType&lt;Secretary&gt;"> 
        <Then> 
          <Line align="Right">______________________    _________________________________________</Line> 
        </Then> 
        <Else> 
          <Line align="Right">{$ElectionManager.SourceData.GetCommitteeMemberInitialByType&lt;Secretary&gt;}    _________________________________________</Line> 
        </Else> 
      </If> 
      <Line align="Left">–ß–ª–µ–Ω—ã –∫–æ–º–∏—Å—Å–∏–∏:</Line> 
            <Line align="Right">______________________    _________________________________________</Line> 
      <Line align="Right">______________________    _________________________________________</Line> 
      <Line align="Right">______________________    _________________________________________</Line> 
      <Line align="Right">______________________    _________________________________________</Line> 
      <Line align="Right">______________________    _________________________________________</Line> 
      <Line align="Right">______________________    _________________________________________</Line> 
      <Line align="Right">______________________    _________________________________________</Line> 
      <Line align="Right">______________________    _________________________________________</Line> 
      <Line align="Right">______________________    _________________________________________</Line> 
      <Line align="Right">______________________    _________________________________________</Line> 
      <Line align="Right">______________________    _________________________________________</Line> 
      <Line align="Right">______________________    _________________________________________</Line> 
      <Line align="Right">______________________    _________________________________________</Line> 
      <Line align="Left"/> 
            <Line align="Left" bold="true">    –ú–ü       –ü—Ä–æ—Ç–æ–∫–æ–ª –ø–æ–¥–ø–∏—Å–∞–Ω "___" _____ {$CurrentDateTime.Year} –≥–æ–¥–∞   –≤ ___ —á–∞—Å–æ–≤ ___ –º–∏–Ω—É—Ç</Line> 
    </PageFooter> 
    <Footer> 
            <Line align="Left">–°–≤–µ–¥–µ–Ω–∏—è –æ –∫–æ–ª–∏—á–µ—Å—Ç–≤–µ –ø–æ—Å—Ç—É–ø–∏–≤—à–∏—Ö –≤ —É—á–∞—Å—Ç–∫–æ–≤—É—é –∏–∑–±–∏—Ä–∞—Ç–µ–ª—å–Ω—É—é –∫–æ–º–∏—Å—Å–∏—é –≤ –¥–µ–Ω—å –≥–æ–ª–æ—Å–æ–≤–∞–Ω–∏—è –∏ –¥–æ –æ–∫–æ–Ω—á–∞–Ω–∏—è   __________
________________________</Line> 
            <Line align="Left">–ø–æ–¥—Å—á–µ—Ç–∞ –≥–æ–ª–æ—Å–æ–≤ –∏–∑–±–∏—Ä–∞—Ç–µ–ª–µ–π –∂–∞–ª–æ–± (–∑–∞—è–≤–ª–µ–Ω–∏–π), –ø—Ä–∏–ª–∞–≥–∞–µ–º—ã—Ö –∫ –ø—Ä–æ—Ç–æ–∫–æ–ª—É                                                                   —Ü–∏—Ñ—Ä–∞–º–∏
ø—Ä–æ–ø–∏—Å—å—é</Line> 
    </Footer> 
</ReportTemplate>
