=== AlikZan/KOIB/Croc.Bpc/Printing/Data/Schemas/ReportTemplate.xsd
<?xml version="1.0" encoding="windows-1251"?> 

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://localhost/Schemas/SIB2003/ReportTemplate"

targetNamespace="http://localhost/Schemas/SIB2003/ReportTemplate" elementFormDefault="qualified"> 

	<xs:element name="ReportTemplate"> 

		<xs:annotation> 

			<xs:documentation>???????? ??????? ??????</xs:documentation> 

		</xs:annotation> 

		<xs:complexType> 

			<xs:sequence> 

				<xs:element name="Parameters" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>????????? ??????</xs:documentation> 

					</xs:annotation> 

					<xs:complexType> 

						<xs:sequence> 

							<xs:element name="Parameter" type="xs:string" maxOccurs="unbounded"> 

								<xs:annotation> 

									<xs:documentation>???????? ?????????</xs:documentation> 

								</xs:annotation> 

							</xs:element> 

						</xs:sequence> 

					</xs:complexType> 

				</xs:element> 

				<xs:element name="Header" type="PlainContent" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>????????? ??????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="PageHeader" type="PlainContent" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>???????????? ?????????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="Table" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>???? ??????</xs:documentation> 

					</xs:annotation> 

					<xs:complexType> 

						<xs:complexContent> 

							<xs:extension base="TableContent"> 

								<xs:attribute name="dotted" type="xs:boolean"> 

									<xs:annotation> 

										<xs:documentation>??????? ?????????? ?????? ???? ? ??????? ???????</xs:documentation> 

									</xs:annotation> 

								</xs:attribute> 

							</xs:extension> 

						</xs:complexContent> 

					</xs:complexType> 

				</xs:element> 

				<xs:element name="PageFooter" type="PlainContent" minOccurs="0"> 


					<xs:annotation> 

						<xs:documentation>???????????? ??????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="Footer" type="PlainContent" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>?????? ??????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

			</xs:sequence> 

			<xs:attribute name="name" type="xs:string" use="required"> 

				<xs:annotation> 

					<xs:documentation>??? ??????</xs:documentation> 

				</xs:annotation> 

			</xs:attribute> 

			<xs:attribute name="restriction" type="xs:string"> 

				<xs:annotation> 

					<xs:documentation>??????????? ?? ?????????? ??????</xs:documentation> 

				</xs:annotation> 

			</xs:attribute> 

			<xs:attribute name="claspFooter" type="xs:boolean" default="true"> 

				<xs:annotation> 

					<xs:documentation>??????? ???????? ??????? ? ??????</xs:documentation> 

				</xs:annotation> 

			</xs:attribute> 

			<xs:attribute name="pageNumbered" type="xs:boolean" default="true"> 

				<xs:annotation> 

					<xs:documentation>??????? ????????????? ?????? ??????? ???????</xs:documentation> 

				</xs:annotation> 

			</xs:attribute> 

		</xs:complexType> 

	</xs:element> 

	<xs:complexType name="IfClause"> 

		<xs:attribute name="condition" type="xs:string" use="required"> 

			<xs:annotation> 

				<xs:documentation>???????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

		<xs:attribute name="not" type="xs:boolean"> 

			<xs:annotation> 

				<xs:documentation>???????? ???????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

	</xs:complexType> 

	<xs:complexType name="PlainIfClause"> 

		<xs:complexContent> 

			<xs:extension base="IfClause"> 

				<xs:sequence> 

					<xs:element name="Then" type="PlainContent" minOccurs="0"> 

						<xs:annotation> 


							<xs:documentation>??????????? ??? ?????????? ???????</xs:documentation> 

						</xs:annotation> 

					</xs:element> 

					<xs:element name="Else" type="PlainContent" minOccurs="0"> 

						<xs:annotation> 

							<xs:documentation>??????????? ??? ???????? ???????</xs:documentation> 

						</xs:annotation> 

					</xs:element> 

				</xs:sequence> 

			</xs:extension> 

		</xs:complexContent> 

	</xs:complexType> 

	<xs:complexType name="TableIfClause"> 

		<xs:complexContent> 

			<xs:extension base="IfClause"> 

				<xs:sequence> 

					<xs:element name="Then" type="TableBody" minOccurs="0"> 

						<xs:annotation> 

							<xs:documentation>??????????? ? ?????? ?????????? ???????</xs:documentation> 

						</xs:annotation> 

					</xs:element> 

					<xs:element name="Else" type="TableBody" minOccurs="0"> 

						<xs:annotation> 

							<xs:documentation>??????????? ? ?????? ???????? ???????</xs:documentation> 

						</xs:annotation> 

					</xs:element> 

				</xs:sequence> 

			</xs:extension> 

		</xs:complexContent> 

	</xs:complexType> 

	<xs:complexType name="PlainContent"> 

		<xs:sequence minOccurs="0" maxOccurs="unbounded"> 

			<xs:choice> 

				<xs:element name="Line" minOccurs="0" maxOccurs="unbounded"> 

					<xs:annotation> 

						<xs:documentation>?????? ??????</xs:documentation> 

					</xs:annotation> 

					<xs:complexType mixed="true"> 

						<xs:complexContent mixed="true"> 

							<xs:extension base="PlainLine"/> 

						</xs:complexContent> 

					</xs:complexType> 

				</xs:element> 

				<xs:element name="If" type="PlainIfClause" minOccurs="0" maxOccurs="unbounded"> 

					<xs:annotation> 

						<xs:documentation>???????? ????????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="For" type="PlainForClause" minOccurs="0" maxOccurs="unbounded"> 

					<xs:annotation> 


						<xs:documentation>????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="SetCurrentRow" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>????????? ?????? ??????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

			</xs:choice> 

		</xs:sequence> 

	</xs:complexType> 

	<xs:complexType name="TableBody"> 

		<xs:sequence minOccurs="0" maxOccurs="unbounded"> 

			<xs:choice> 

				<xs:element name="Line" minOccurs="0" maxOccurs="unbounded"> 

					<xs:annotation> 

						<xs:documentation>?????? ???????</xs:documentation> 

					</xs:annotation> 

					<xs:complexType> 

						<xs:complexContent> 

							<xs:extension base="TableLine"> 

								<xs:attributeGroup ref="IfCondition"/> 

							</xs:extension> 

						</xs:complexContent> 

					</xs:complexType> 

				</xs:element> 

				<xs:element name="If" type="TableIfClause" minOccurs="0" maxOccurs="unbounded"> 

					<xs:annotation> 

						<xs:documentation>???????? ????????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="For" type="TableForClause" minOccurs="0" maxOccurs="unbounded"> 

					<xs:annotation> 

						<xs:documentation>????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

				<xs:element name="SetCurrentRow" minOccurs="0"> 

					<xs:annotation> 

						<xs:documentation>????????? ?????? ??????</xs:documentation> 

					</xs:annotation> 

				</xs:element> 

			</xs:choice> 

		</xs:sequence> 

	</xs:complexType> 

	<xs:complexType name="PlainForClause"> 

		<xs:sequence> 

			<xs:element name="Body" type="PlainContent"> 

				<xs:annotation> 

					<xs:documentation>???? ?????</xs:documentation> 

				</xs:annotation> 


			</xs:element> 

		</xs:sequence> 

		<xs:attributeGroup ref="ForCondition"/> 

	</xs:complexType> 

	<xs:complexType name="LinePart" mixed="true"> 

		<xs:sequence> 

			<xs:element name="Parts" minOccurs="0"> 

				<xs:annotation> 

					<xs:documentation>?????????</xs:documentation> 

				</xs:annotation> 

				<xs:complexType> 

					<xs:sequence> 

						<xs:element name="Part" type="LinePart" minOccurs="0" maxOccurs="unbounded"> 

							<xs:annotation> 

								<xs:documentation>???????? ?????????</xs:documentation> 

							</xs:annotation> 

						</xs:element> 

					</xs:sequence> 

				</xs:complexType> 

			</xs:element> 

		</xs:sequence> 

		<xs:attributeGroup ref="IfCondition"/> 

	</xs:complexType> 

	<xs:complexType name="TableForClause"> 

		<xs:sequence> 

			<xs:element name="Body" type="TableBody"> 

				<xs:annotation> 

					<xs:documentation>???? ?????</xs:documentation> 

				</xs:annotation> 

			</xs:element> 

		</xs:sequence> 

		<xs:attributeGroup ref="ForCondition"/> 

	</xs:complexType> 

	<xs:attributeGroup name="ForCondition"> 

		<xs:attribute name="each" type="xs:string" use="required"> 

			<xs:annotation> 

				<xs:documentation>?????????? ?????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

		<xs:attribute name="in" type="xs:string" use="required"> 

			<xs:annotation> 

				<xs:documentation>?????????, ?? ??????? ??????????? ????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

	</xs:attributeGroup> 

	<xs:attributeGroup name="IfCondition"> 

		<xs:attribute name="condition" type="xs:string"> 

			<xs:annotation> 

				<xs:documentation>???????</xs:documentation> 

			</xs:annotation> 


		</xs:attribute> 

		<xs:attribute name="not" type="xs:boolean"> 

			<xs:annotation> 

				<xs:documentation>???????? ????????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

	</xs:attributeGroup> 

	<xs:complexType name="TableContent"> 

		<xs:sequence> 

			<xs:element name="Header"> 

				<xs:annotation> 

					<xs:documentation>???????? ???????? ???????</xs:documentation> 

				</xs:annotation> 

				<xs:complexType> 

					<xs:sequence> 

						<xs:element name="Col" maxOccurs="unbounded"> 

							<xs:annotation> 

								<xs:documentation>???????? ???????</xs:documentation> 

							</xs:annotation> 

							<xs:complexType mixed="true"> 

								<xs:attributeGroup ref="FontDefinition"/> 

								<xs:attribute name="width" type="xs:int"> 

									<xs:annotation> 

										<xs:documentation>?????? ??????? ? %</xs:documentation> 

									</xs:annotation> 

								</xs:attribute> 

								<xs:attribute name="count" type="xs:string"> 

									<xs:annotation> 

										<xs:documentation>?????????, ?? ?????????? ????????? ??????? ????? ????????? ???????</xs:documentation> 

									</xs:annotation> 

								</xs:attribute> 

							</xs:complexType> 

						</xs:element> 

					</xs:sequence> 

				</xs:complexType> 

			</xs:element> 

			<xs:element name="Body" type="TableBody"> 

				<xs:annotation> 

					<xs:documentation>???? ???????</xs:documentation> 

				</xs:annotation> 

			</xs:element> 

		</xs:sequence> 

	</xs:complexType> 

	<xs:attributeGroup name="FontDefinition"> 

		<xs:attribute name="fontSize" type="xs:string"> 

			<xs:annotation> 

				<xs:documentation>?????? ??????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

		<xs:attribute name="bold" type="xs:boolean"> 


			<xs:annotation> 

				<xs:documentation>??????? ??????? ??????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

		<xs:attribute name="italic" type="xs:boolean"> 

			<xs:annotation> 

				<xs:documentation>??????? ?????????? ??????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

		<xs:attribute name="align" type="Croc.SibApp.Printing.LineAlign"> 

			<xs:annotation> 

				<xs:documentation>????????????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

	</xs:attributeGroup> 

	<xs:complexType name="PlainLine" mixed="true"> 

		<xs:complexContent mixed="true"> 

			<xs:extension base="LinePart"> 

				<xs:attributeGroup ref="FontDefinition"/> 

				<xs:attribute name="split" type="xs:string"> 

					<xs:annotation> 

						<xs:documentation>??????(?) ?? ??????? ?????? ??????????? ?? ?????????</xs:documentation> 

					</xs:annotation> 

				</xs:attribute> 

				<xs:attribute name="trim" type="xs:boolean"> 

					<xs:annotation> 

						<xs:documentation>??????? ???????? ???????? ? ????? ?????? ??????</xs:documentation> 

					</xs:annotation> 

				</xs:attribute> 

			</xs:extension> 

		</xs:complexContent> 

	</xs:complexType> 

	<xs:complexType name="TableLine"> 

		<xs:sequence> 

			<xs:element name="Cols"> 

				<xs:annotation> 

					<xs:documentation>??????? ??????</xs:documentation> 

				</xs:annotation> 

				<xs:complexType> 

					<xs:sequence> 

						<xs:element name="Col" maxOccurs="unbounded"> 

							<xs:annotation> 

								<xs:documentation>???????</xs:documentation> 

							</xs:annotation> 

							<xs:complexType mixed="true"> 

								<xs:complexContent mixed="true"> 

									<xs:extension base="LinePart"> 

										<xs:attribute name="each" type="xs:string"> 

											<xs:annotation> 

												<xs:documentation>?????????? ?????</xs:documentation> 


											</xs:annotation> 

										</xs:attribute> 

										<xs:attribute name="in" type="xs:string"> 

											<xs:annotation> 

												<xs:documentation>?????????, ?? ??????? ???????? ???????</xs:documentation> 

											</xs:annotation> 

										</xs:attribute> 

									</xs:extension> 

								</xs:complexContent> 

							</xs:complexType> 

						</xs:element> 

					</xs:sequence> 

				</xs:complexType> 

			</xs:element> 

		</xs:sequence> 

		<xs:attributeGroup ref="ColDefinition"/> 

		<xs:attribute name="newPage" type="xs:boolean" default="false"> 

			<xs:annotation> 

				<xs:documentation>??????? ???????? ?? ????????? ????????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

	</xs:complexType> 

	<xs:attributeGroup name="ColDefinition"> 

		<xs:attributeGroup ref="FontDefinition"/> 

		<xs:attribute name="dotted" type="xs:boolean"> 

			<xs:annotation> 

				<xs:documentation>??????? ?????????? ?????? ???????</xs:documentation> 

			</xs:annotation> 

		</xs:attribute> 

	</xs:attributeGroup> 

	<xs:simpleType name="Croc.SibApp.Printing.LineAlign"> 

		<xs:annotation> 

			<xs:documentation>Croc.SibApp.Printing.LineAlign</xs:documentation> 

		</xs:annotation> 

		<xs:restriction base="xs:string"> 

			<xs:enumeration value="Left"> 

				<xs:annotation> 

					<xs:documentation>???????????? ?? ?????? ????</xs:documentation> 

				</xs:annotation> 

			</xs:enumeration> 

			<xs:enumeration value="Right"> 

				<xs:annotation> 

					<xs:documentation>???????????? ?? ??????? ????</xs:documentation> 

				</xs:annotation> 

			</xs:enumeration> 

			<xs:enumeration value="Center"> 

				<xs:annotation> 

					<xs:documentation>???????????? ?? ??????</xs:documentation> 

				</xs:annotation> 

			</xs:enumeration> 


		</xs:restriction> 

	</xs:simpleType> 

</xs:schema>

=== AlikZan/KOIB/Croc.Bpc/Printing/Data/Templates/SourceData.xml
<?xml version="1.0" encoding="utf-8"?> 
<ReportTemplate font="Verdana" font-size="8" claspFooter="true" name="SourceData" restriction="Scanner.Voting.HasSourceData" 
                margin-left="15" margin-top="20" margin-right="25" margin-bottom="30" 
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                  xmlns="http://localhost/Schemas/SIB2003/ReportTemplate" 
                  xsi:schemaLocation="http://localhost/Schemas/SIB2003/ReportTemplate ReportTemplate.xsd"> 
  <Parameters> 
    <Parameter>SourceData</Parameter> 
    <Parameter>UIK</Parameter> 
  </Parameters> 
  <Header> 
    <Line fontSize="+2" bold="true" italic="false" align="Center">Исходные данные для УИК N {$@UIK}</Line> 
    <Line>Состав УИК: {$ScannersInfo.GetScannerInfos}</Line> 
    <If condition="@SourceData.IsReal"> 
      <Else> 
        <Line>ТРЕНИРОВОЧНЫЙ РЕЖИМ</Line> 
      </Else> 
    </If> 




    <Line>СКАНЕР N {$ScannersInfo.LocalScannerSerialNumber}</Line> 
    <Line>ДАТА ГОЛОСОВАНИЯ: {$@SourceData.ElectionDate|dd.MM.yyyy}</Line> 
    <Line>ДАННЫЕ ПРЕДНАЗНАЧЕНЫ ДЛЯ УИК: {$@SourceData.Targets|0000|Num}</Line> 
    <Line>КОЛИЧЕСТВО ТИПОВ БЮЛЛЕТЕНЕЙ: {$@SourceData.Blanks.Length}</Line> 
    <Line>ПОСЛЕДОВАТЕЛЬНОСТЬ СМЕНЫ РЕЖИМОВ: {$@SourceData.Modes}</Line> 


    <If condition="@SourceData.VotingModeTimes"> 
      <Then> 
        <Line>{$TAB}Время начала стационарного режима: {$@SourceData.MainVotingStartTime|t}</Line> 
        <Line>{$TAB}Время окончания стационарного режима: {$@SourceData.MainVotingEndTime|t}</Line> 
      </Then> 
    </If> 
    <If condition="@SourceData.CommitteeMembers"> 
      <Then> 
        <Line>СОСТАВ ЧЛЕНОВ УЧАСТКОВОЙ ИЗБИРАТЕЛЬНОЙ КОМИССИИ</Line> 
        <For each="Member" in="@SourceData.CommitteeMembers"> 
          <Body> 
            <If condition="@Member.LastName"> 
              <Then> 
                <Line> 
                  <Parts> 
                    <Part>{$TAB}{$TAB}{$TAB}{$@Member.Type|t}: </Part> 
                    <Part condition="@Member.LastName">{$@Member.LastName|#u}</Part> 
                    <Part condition="@Member.FirstName"> {$@Member.FirstName}</Part> 
                    <Part condition="@Member.Patronymic"> {$@Member.Patronymic}</Part> 
                  </Parts> 
                </Line> 
              </Then> 
            </If> 
            <If condition="@Member.LastName"> 
              <Else> 
                <Line> 
                  <Parts> 
                    <Part>{$TAB}{$TAB}{$TAB}{$@Member.Type|t}: </Part> 
                    <Part>ФИО НЕ ЗАДАНО</Part> 
                  </Parts> 
                </Line> 
              </Else> 
            </If> 
          </Body> 
        </For> 
      </Then> 
    </If> 
    <Line>БЮЛЛЕТЕНИ:</Line> 


    <For each="Blank" in="@SourceData.Blanks"> 
      <Body> 
        <Line>{$TAB}БЮЛЛЕТЕНЬ N {$@Blank.Id}</Line> 
        <Line>{$TAB}{$TAB}ВЫБОРЫ: {$@Blank.Elections}</Line> 
      </Body> 
    </For> 
    <Line>ВЫБОРЫ:</Line> 
    <For each="Election" in="@SourceData.Elections"> 
      <Body> 
        <Line>{$TAB}{$@Election.@Current}. {$@Election.Name}</Line> 
        <Line>{$TAB}{$TAB}РЕЖИМЫ ГОЛОСОВАНИЯ: {$@Election.Modes}</Line> 
        <Line condition="@Election.StampCommittees">{$TAB}{$TAB}НОМЕРА ВЫШЕСТОЯЩИХ КОМИССИЙ: {$@Election.StampCommittees|0000|Num}</Line> 
        <Line>{$TAB}{$TAB}ЧИСЛО МАНДАТОВ: {$@Election.MaxMarks}</Line> 
        <If condition="@Election.NoneAboveExists"> 
          <Then> 
            <Line>{$TAB}{$TAB}НАЛИЧИЕ ОТМЕТКИ "ПРОТИВ ВСЕХ": {$@Election.NoneAboveExists}</Line> 
          </Then> 
        </If> 
        <Line>{$TAB}{$TAB}ЧИСЛО ПОЗИЦИЙ: {$@Election.Candidates.Length}</Line> 
        <Line>{$TAB}{$TAB}ПОЗИЦИИ:</Line> 
        <For each="Candidate" in="@Election.Candidates"> 
          <Body> 
            <Line> 
              <Parts> 
                <Part>{$TAB}{$TAB}{$TAB}{$@Candidate.@Current}. </Part> 
                <Part condition="@Candidate.LastName">{$@Candidate.LastName|#u}</Part> 
                <Part condition="@Candidate.FirstName"> {$@Candidate.FirstName}</Part> 
                <Part condition="@Candidate.Patronymic"> {$@Candidate.Patronymic}</Part> 
                <Part condition="@Candidate.DisabledInSourceData"> (позиция снята)</Part> 
                <Part condition="@Candidate.DisabledLocally"> (позиция снята на УИК)</Part> 
              </Parts> 
            </Line> 
          </Body> 
        </For> 
        <Line>{$TAB}{$TAB}НАИМЕНОВАНИЕ ПРОТОКОЛА: {$@Election.Protocol.Name}</Line> 
        <If condition="@Election.Protocol.DisabledString"> 
          <Then> 
            <Line>{$TAB}{$TAB}СТРОКА ДЛЯ СНЯТЫХ ПОЗИЦИЙ: {$@Election.Protocol.DisabledString}</Line> 
          </Then> 
          <Else> 
            <Line>{$TAB}{$TAB}СНЯТЫЕ ПОЗИЦИИ НЕ ВКЛЮЧАЮТСЯ В ОТЧЕТ</Line> 
          </Else> 
        </If> 
        <If condition="@Election.Protocol.Lines"> 
          <Then> 
            <Line>{$TAB}{$TAB}СТРОКИ ПРОТОКОЛА:</Line> 
            <For each="Line" in="@Election.Protocol.Lines"> 
              <Body> 
                <Line>{$TAB}{$TAB}{$TAB}{$@Line.Num}{$@Line.AdditionalNum}. {$@Line.Name}. ({$@Line.Type})</Line> 
              </Body> 
            </For> 
          </Then> 
          <Else> 
            <Line>{$TAB}{$TAB}СТРОКИ ПРОТОКОЛА: НЕТ</Line> 
          </Else> 
        </If> 
        <If condition="ElectionManager.NeedExecuteCheckExpressions"> 
          <Then> 
            <Line/> 
            <Line>{$TAB}{$TAB}КОНТРОЛЬНЫЕ СООТНОШЕНИЯ:</Line> 
            <For each="Check" in="@Election.Protocol.Checks"> 
              <Body> 
                <Line condition="@Check.Enabled"> 
                  <Parts> 
                    <Part>{$TAB}{$TAB}{$TAB}</Part> 
                    <Part condition="@Check.Mild"> 
                      <Parts> 
                        <Part>[ЛОГИЧЕСКОЕ] </Part> 
                      </Parts> 
                    </Part> 
                    <Part>{$@Check.GetExpansion&lt;$@Election.Protocol&gt;}</Part> 
                  </Parts> 
                </Line> 
              </Body> 
            </For> 
          </Then> 
          <Else> 
            <Line>{$TAB}{$TAB}КОНТРОЛЬНЫЕ СООТНОШЕНИЯ: НЕТ</Line> 
          </Else> 
        </If> 
        <Line/> 
      </Body> 
    </For> 
  </Header> 
  <PageFooter> 
    <Line align="Left">Председатель участковой избирательной комиссии</Line> 
    <If not="true" condition="@SourceData.GetCommitteeMemberInitialByType&lt;Chairman&gt;"> 
      <Then> 
        <Line align="Right">______________________    _________________________________________</Line> 
      </Then> 
      <Else> 
        <Line align="Right">{$@SourceData.GetCommitteeMemberInitialByType&lt;Chairman&gt;}  _________________________________________</Line> 
      </Else> 
    </If> 
    <Line align="Right">(фамилия, инициалы)                       (подпись либо причина отсутствия,      </Line> 
    <Line align="Right">                                     отметка об особом мнении)           </Line> 
    <Line align="Left">Заместитель председателя комиссии</Line> 
    <If not="true" condition="@SourceData.GetCommitteeMemberInitialByType&lt;ChairmanAssistant&gt;"> 
      <Then> 
        <Line align="Right">______________________    _________________________________________</Line> 
      </Then> 
      <Else> 
        <Line align="Right">{$@SourceData.GetCommitteeMemberInitialByType&lt;ChairmanAssistant&gt;}  _________________________________________</Line> 
      </Else> 
    </If> 
    <Line align="Left">Секретарь комиссии</Line> 
    <If not="true" condition="@SourceData.GetCommitteeMemberInitialByType&lt;Secretary&gt;"> 
      <Then> 
        <Line align="Right">______________________    _________________________________________</Line> 
      </Then> 
      <Else> 
        <Line align="Right">{$@SourceData.GetCommitteeMemberInitialByType&lt;Secretary&gt;}  _________________________________________</Line> 
      </Else> 
    </If> 
  </PageFooter> 
</ReportTemplate>
